name: Gradle Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17

        uses: actions/setup-java@v1
        with:
          java-version: 1.17

      - name: Grant execute permission for PochodApp gradlew
        run: chmod +x gradlew

      - name: Build PochodApp with Gradle
        run: ./gradlew clean build